---
engines:
  csslint:
    enabled: false
  
exclude_paths:
  - '**/*.Designer.cs'
  - '**/obj/**'
  - '**/bin/**'
  - '**/packages/**'
  - '**/*.Version.cs'
  - '**/*.AssemblyInfo.cs'
  - '**/*.AssemblyAttributes.cs'
  - 'Publish.ps1'
