namespace PanoramicData.NCalcExtensions;

public static class ExtensionFunction
{
	public static readonly string CanEvaluate = "canEvaluate";
	public static readonly string Capitalise = "capitalise";
	public static readonly string Capitalize = "capitalize";
	public static readonly string Cast = "cast";
	public static readonly string ChangeTimeZone = "changeTimeZone";
	public static readonly string Concat = "concat";
	public static readonly string Contains = "contains";
	public static readonly string Convert = "convert";
	public static readonly string Count = "count";
	public static readonly string DateTime = "dateTime";
	public static readonly string DateTimeAsEpochMs = "dateTimeAsEpochMs";
	public static readonly string EndsWith = "endsWith";
	public static readonly string Format = "format";
	public static readonly string Humanise = "humanise";
	public static readonly string Humanize = "humanize";
	public static readonly string If = "if";
	public static readonly string In = "in";
	public static readonly string IndexOf = "indexOf";
	public static readonly string IsInfinite = "isInfinite";
	public static readonly string IsNaN = "isNaN";
	public static readonly string IsNull = "isNull";
	public static readonly string IsNullOrWhiteSpace = "isNullOrWhiteSpace";
	public static readonly string IsNullOrEmpty = "isNullOrEmpty";
	public static readonly string IsSet = "isSet";
	public static readonly string ItemAtIndex = "itemAtIndex";
	public static readonly string Join = "join";
	public static readonly string JPath = "jPath";
	public static readonly string LastIndexOf = "lastIndexOf";
	public static readonly string Length = "length";
	public static readonly string List = "list";
	public static readonly string NullCoalesce = "nullCoalesce";
	public static readonly string PadLeft = "padLeft";
	public static readonly string Parse = "parse";
	public static readonly string ParseInt = "parseInt";
	public static readonly string RegexGroup = "regexGroup";
	public static readonly string RegexIsMatch = "regexIsMatch";
	public static readonly string Replace = "replace";
	public static readonly string Skip = "skip";
	public static readonly string Split = "split";
	public static readonly string StartsWith = "startsWith";
	public static readonly string Substring = "substring";
	public static readonly string Switch = "switch";
	public static readonly string Take = "take";
	public static readonly string Throw = "throw";
	public static readonly string TimeSpan = "timespan";
	public static readonly string TimeSpanCamel = "timeSpan";
	public static readonly string ToDateTime = "toDateTime";
	public static readonly string ToLower = "toLower";
	public new static readonly string ToString = "toString";
	public static readonly string ToUpper = "toUpper";
	public static readonly string Try = "try";
	public static readonly string TypeOf = "typeOf";
}